# Generated by Django 4.2.30 on 2026-06-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_avatar_alter_user_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name='user',
            name='governorate',
            field=models.CharField(blank=True, choices=[('cairo', 'Cairo'), ('giza', 'Giza'), ('alexandria', 'Alexandria'), ('beni_suef', 'Beni Suef'), ('qalyubia', 'Qalyubia'), ('sharqia', 'Sharqia'), ('dakahlia', 'Dakahlia'), ('minya', 'Minya'), ('fayoum', 'Fayoum'), ('asyut', 'Asyut'), ('sohag', 'Sohag'), ('luxor', 'Luxor'), ('aswan', 'Aswan'), ('port_said', 'Port Said'), ('suez', 'Suez'), ('ismailia', 'Ismailia'), ('damietta', 'Damietta'), ('kafr_sheikh', 'Kafr El-Sheikh'), ('gharbia', 'Gharbia'), ('menofia', 'Menofia'), ('beheira', 'Beheira'), ('qena', 'Qena'), ('red_sea', 'Red Sea'), ('new_valley', 'New Valley'), ('matrouh', 'Matrouh'), ('north_sinai', 'North Sinai'), ('south_sinai', 'South Sinai')], db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='name_ar',
            field=models.CharField(blank=True, help_text='Arabic display name (الاسم بالعربية).', max_length=120),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['governorate', 'city'], name='users_user_governo_d8868b_idx'),
        ),
    ]
