# Generated by Django 4.2.30 on 2026-05-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='icon',
            field=models.CharField(blank=True, help_text='Optional icon name/key for the mobile app', max_length=64),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional indicative hourly rate.', max_digits=8, null=True),
        ),
        migrations.AddIndex(
            model_name='workerprofile',
            index=models.Index(fields=['is_available', '-average_rating'], name='workers_wor_is_avai_d3b12e_idx'),
        ),
        migrations.AddIndex(
            model_name='workerprofile',
            index=models.Index(fields=['profession'], name='workers_wor_profess_f3c242_idx'),
        ),
    ]
