# Generated by Django 4.2.30 on 2026-06-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_alter_servicecategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='description_ar',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='name_ar',
            field=models.CharField(blank=True, help_text='Arabic name (الاسم بالعربية)', max_length=100),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='bio_ar',
            field=models.TextField(blank=True, help_text='Bio in Arabic (نبذة)', max_length=1000),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='currency',
            field=models.CharField(default='EGP', max_length=3),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='ID-verified worker (شغل موثّق).'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='profession_ar',
            field=models.CharField(blank=True, help_text='Profession in Arabic (المهنة)', max_length=200),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Indicative hourly rate in EGP.', max_digits=8, null=True),
        ),
        migrations.AddIndex(
            model_name='workerprofile',
            index=models.Index(fields=['is_verified'], name='workers_wor_is_veri_04b2ff_idx'),
        ),
    ]
