# Generated by Django 4.2.30 on 2026-06-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_servicecategory_description_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='accept_rate',
            field=models.FloatField(default=0.0, help_text='Percentage 0-100.'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='completion_rate',
            field=models.FloatField(default=0.0, help_text='Percentage 0-100.'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Pinned to the top of listings.'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='languages',
            field=models.CharField(blank=True, default='ar', help_text='Comma-separated language codes (ar,en,fr,...)', max_length=80),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='minimum_charge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum call-out fee in EGP.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='response_time_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Typical response time to a new order, in minutes.'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='service_radius_km',
            field=models.PositiveSmallIntegerField(default=10, help_text='How far the worker is willing to travel.'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='specialties',
            field=models.CharField(blank=True, help_text="Comma-separated specialties (e.g. 'AC install,fridge repair').", max_length=400),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='specialties_ar',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='working_hours_end',
            field=models.PositiveSmallIntegerField(default=22),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='working_hours_start',
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='works_friday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='workerprofile',
            index=models.Index(fields=['is_featured', '-average_rating'], name='workers_wor_is_feat_1df44a_idx'),
        ),
        migrations.AddIndex(
            model_name='workerprofile',
            index=models.Index(fields=['latitude', 'longitude'], name='workers_wor_latitud_162166_idx'),
        ),
    ]
