# Generated by Django 4.2.30 on 2026-06-18 02:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0005_servicecategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategory',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='categories/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'webp', 'gif'])]),
        ),
    ]
