# Generated by Django 4.2.30 on 2026-06-06 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_orders_orde_status_079368_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, help_text='What the client wrote about the issue.', max_length=2000),
        ),
        migrations.AddField(
            model_name='order',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='urgency',
            field=models.CharField(choices=[('LOW', 'Whenever'), ('NORMAL', 'Today'), ('HIGH', 'Now / Emergency')], default='NORMAL', max_length=10),
        ),
        migrations.CreateModel(
            name='OrderAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video')], default='image', max_length=10)),
                ('file', models.FileField(upload_to='order_attachments/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='For audio/video: clip length in seconds.', null=True)),
                ('size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='orders.order')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
