# Generated by Django 4.2.30 on 2026-05-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['worker', '-created_at'], name='ratings_rat_worker__8c5bd5_idx'),
        ),
    ]
