# Generated by Django 4.2.30 on 2026-05-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['client', '-created_at'], name='favorites_f_client__1efee8_idx'),
        ),
    ]
